### ISSUE TITLE
Preview mode

### ISSUE THREAD

**Issue by 45deg** [BrainPad/cliboa#130]
Embulk has preview executor
https://www.embulk.zrg/docs/built-in.html#preview-executor

```
exec:
  preview_sample_buffer_bytes: 65536 # 64KB
in:
  type: ...
  ...
out:
  type: ...
  ...
```
