### ISSUE TITLE
Propose: Add new parallel notation for scenario files

### ISSUE THREAD

**Issue by Wisteria30** [BrainPad/cliboa#252]
The parallel notation used in the current scenario file depends on a multi_process_count set in one global for the number of processes. So, if there are multiple parallels under a scenario, there is a problem that the number of processes for each parallel cannot be set.

```yml
scenario:
- multi_process_count: 2
- parallel:
  - step:
    class: ...
    arguments:
      ...
  - step:
    class: ...
    arguments:
      ...
- parallel:
  - step:
    class: ...
    arguments:
      ...
  - step:
    class: ...
    arguments:
      ...
```

So, I propose the following new notation for parallels, which can be used to write configs about parallels.

```yml
scenario:
- parallel_with_config:
  config:
    multi_process_count: 5
  steps:
    - step:
      class: ...
      arguments:
        ...
    - step:
      class: ...
      arguments:
        ...
- parallel_with_config:
  config:
    multi_process_count: 3
  steps:
    - step:
      class: ...
      arguments:
        ...
    ...
```

This new notation will allow you to configure and run each parallel by writing the parallel configuration and the steps to be executed in parallel_with_config.

This is a new notation for parallels, and does not destroy the current notation for paralles.

I'm not sure how much of a change this new notation will cause, so I'd like to start by investigating it.

**Comment by Wisteria30** [comment]
As a result of Survey, the current parallel is executed by the following steps.

1. multi_process_count is managed as a property by the Queue(StepQueue) that manages the job.
2. add the scenario to the queue of job management by add_queue, in order from the top. At this time, in case of single process, one step is stored as an instance in a list of length 1, and added to the Queue. In the case of parallel, store the scenario as an instance in a list of length n, including all n steps below the parallel, and add it to the Queue.
3. At the runtime, pop the items from the stored Queue in order, generate an appropriate StepExecuter for the item, and execute it. If the length of the list of popped items is 1, it is executed as a single process. If the length of the list is more than 1, it determines the number of processes by referring to the multi_process_count property of the Queue that manages the job, and executes it as a multi-process.

So, in order to implement the new notation `process_with_config`, the following changes are considered.

1. create a namedTuple ParallelWithConfig with a list of instantiated contents of steps and a dict about config under parallel_with_config.
2. If a block of parallel_with_config is found in the current add_queue(), as is done in parallel, separate steps and config using dict[key], create an instance, and add it to the queue as ParallelWithConfig and add it to the Queue.
3. At the runtime, if the item popped from the Queue is ParallelWithConfig, create a MultiProcWithConifgExecutor that takes a list of steps and config as arguments, and execute it inside the MultiProcWithConifgExecutor. config has information about multi_process_ count, and use that information to control the number of processes in the Pool.


If there are any strange points or questions, please let me know.

**Comment by Wisteria30** [comment]
Sorry, the parallel notation I proposed earlier was wrong.(In the previous notation, parallel_with_config and config, steps were in the same level)
The correct one is here.

```
scenario:
- parallel_with_config:
    config:
      multi_process_count: 5
    steps:
    - step:
      class: ...
      arguments:
        ...
    - step:
      class: ...
      arguments:
        ...
- parallel_with_config:
    config:
      multi_process_count: 3
    steps:
    - step:
      class: ...
      arguments:
        ...
```
