### ISSUE TITLE
Allow environment values to be used in scenario.yaml

### ISSUE THREAD

**Issue by bo-naoki-okamoto** [BrainPad/cliboa#310]

**Comment by bo-naoki-okamoto** [comment]
Environment variables will be available in the scenario.yml
(like an example below)
```
scenario:
- step: 
  class: SftpDownload
  arguments:
    host: dummy_host
    user: root
    password: {{ env.psaaword }} 
    src_dir: /resorces/files
    src_pattern: test_file\.csv
    dest_dir: /usr/local/sftp/download
```
